config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, :only => [:new, :create, :show]

  resources :welcome, :only => [:index]

  namespace :admin do
    resources :users, :only => [:index, :show, :edit, :update, :destroy]
  end

  namespace :editor do
    resources :gifs, :only => [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/gif.rb
class Gif < ApplicationRecord
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true

  # has_many :users, class_name: "User", primary_key: :user_role_id, foreign_key: :role

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :username, uniqueness: true
  # validates :password, presence: true
  validates :name, presence: true
  validates :email, presence: true

  has_secure_password

  enum site_role: [:user, :editor, :admin]

  belongs_to :role
  belongs_to :site_role,
              class_name: "Role",
              primary_key: :user_role_id,
              foreign_key: :site_role
   
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :confirm_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @roles = Role.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    new_role = Role.find(params[:user][:role])
    @user.role = new_role
    @user.site_role = new_role
    if @user.save
      flash["success"] = "#{@user.username} user details were successfully updated"
      redirect_to admin_user_path(@user)
    else
      flash["danger"] = @user.errors.full_messages
      @roles = Role.all
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end

  def confirm_admin
    if current_user
      if current_user.admin?
      else
        flash["danger"] = "You were not authorized to view that page, here is your page instead."
        redirect_to user_path(current_user)
      end
    else
      flash["danger"] = "You need to be signed in to view that page..."
      redirect_to login_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :matching_user

  before_action :require_login

  private

  def require_login
    current_user
  end

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  def matching_user
    if !session[:user_id].to_i.eql?(params[:id].to_i)
      flash["danger"] = "Not authorized to view the requested page. Here is your page instead!"
      redirect_to user_path(session[:user_id])
    end
  end


end

app/controllers/editor/gifs_controller.rb
require 'giphy'

class Editor::GifsController < ApplicationController
  before_action :confirm_editor

  def index
    @gifs = Gif.all
  end

  def new
    new_random_giphy = Giphy.new.random
    @gif = Gif.new
    @gif.url = new_random_giphy["url"] 
    @gif.image_original_url = new_random_giphy["image_original_url"] 
    @gif.fixed_width_downsampled_url = new_random_giphy["fixed_width_downsampled_url"] 
    @gif.keyword = params["search"]["keyword"]
  end

  def create
    gif = Gif.new(gif_params)
    gif.category = Category.find_or_create_by(title: gif.keyword)
    gif.save
    redirect_to editor_gifs_path
  end

  def destroy
    Gif.destroy(params[:id])
    redirect_to editor_gifs_path
  end

  private

  def gif_params
    params.require(:gif).permit(:url, :image_original_url, :fixed_width_downsampled_url, :keyword)
  end

  def confirm_editor
    if current_user
      if current_user.admin? || current_user.editor?
      else
        flash["danger"] = "You were not authorized to view that page, here is your page instead."
        redirect_to user_path(current_user)
      end
    else
      flash["danger"] = "You need to be signed in to view that page..."
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash["danger"] = "Invalid login"
      redirect_to "/login"
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :matching_user, :only => [:show]

  def show
    current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    user_role = Role.find_by(title: "user")
    @user.role = user_role
    @user.site_role = user_role
    @user.save
    if @user
      flash["success"] = "Successfully registered user: #{@user.username}. Please log in!"
      redirect_to login_path
    else
      flash["warning"] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<%= form_for @user, url: admin_user_path(@user), :html => {:class => "form-horizontal"} do |f| %>
  <div class = "form-group">
    <%= f.label :username, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :username, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :email, :class => "col-sm-2 control-label text-right" %>
    <div class = "col-sm-10">
      <%= f.email_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :password, :class => "col-sm-2 control-label text-right" %>
    <div class = "col-sm-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :role, :class => "col-sm-2 control-label text-right" %>
    <div class = "col-sm-10">
      <%= f.select :role, @roles.collect {|r| [r.title, r.id]}, {:selected => @user.role.id.to_s}, {:class => "form-control"} %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "col-sm-offset-2 col-sm-10">
      <%= f.submit "Update User Details", :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>User List</h1>

<table class = "table">
  <tr>
    <th>Username</th>
    <th>Site Role</th>
    <th class = "text-center" colspan = "2">Action</th>
  </tr>
  <% @users.each do |user|%>
    <tr>
      <td><%= link_to user.username, admin_user_path(user) %></td>
      <td><%= user.role.title %></td>
      <td class = "text-center"><%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-warning" %></td>
      <td class = "text-center"><%= link_to "Delete", user_path(user), method: :delete, class: "btn btn-danger" %></td>
    </tr>
  <% end  %>
</table>

app/views/admin/users/show.html.erb
<form class = "form-horizontal container">
  <div class = "form-group">
    <%= label_tag "Username: ", nil, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= text_field_tag :username, @user.username, class: "form-control", disabled: true %>
    </div>
  </div>

  <div class = "form-group">
    <%= label_tag "Name: ", nil, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= text_field_tag :name, @user.name, class: "form-control", disabled: true %>
    </div>
  </div>

  <div class = "form-group">
    <%= label_tag "Email: ", nil, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= text_field_tag :email, @user.email, class: "form-control", disabled: true %>
    </div>
  </div>

  <div class = "form-group">
    <%= label_tag "Role: ", nil, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= text_field_tag :role, @user.role.title, class: "form-control", disabled: true %>
    </div>
  </div>
</form>

app/views/editor/gifs/index.html.erb
<div class = "container">
  <%= form_for :search, url: new_editor_gif_path, method: :get, :html => {:class => "form-horizontal"} do |f| %>
    <div class = "form-group">
      <%= f.label :keyword, :class => "col-sm-2 control-label" %>
      <div class = "col-sm-2">
        <%= f.text_field :keyword, :class => "form-control" %>
      </div>
      <div class = "col-sm-2">
        <%= f.submit "Generate Gifs", :class => "btn btn-default" %>
      </div>
    </div>
  <% end %>

  <h3>Gif List</h3>

  <table class = "table">
    <tr>
      <th>DB ID</th>
      <th>Image</th>
      <th>Category</th>
      <th>Action</th>
    </tr>
    <% @gifs.each do |gif|%>
      <tr>
        <td><%= link_to gif.id, gif.url %></td>
        <td><img src="<%= gif.fixed_width_downsampled_url %>" class="img-responsive" alt="Responsive image"></td>
        <td><%= gif.category.title %></td>
        <td class = "text-center"><%= link_to "Delete", editor_gif_path(gif), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end  %>
  </table>
</div>

app/views/editor/gifs/new.html.erb
  <div class = "container">
    <%= form_for @gif, url: editor_gifs_path, :html => {:class => "form-horizontal"} do |f| %>
      <div class = "form-group">
        <div class = "col-md-offset-2 col-sm-2">
          <%= f.submit "Add to Collection", :class => "btn btn-default" %>
        </div>
      </div>
      <div class = "form-group">
        <%= f.label :url, :class => "col-sm-2 control-label" %>
        <div class = "col-sm-10">
          <%= f.text_field :url, :class => "form-control", readonly: true %>
        </div>
      </div>
      <div class = "form-group">
        <%= f.label :image_original_url, :class => "col-sm-2 control-label" %>
        <div class = "col-sm-10">
          <%= f.text_field :image_original_url, :class => "form-control", readonly: true %>
        </div>
      </div>
      <div class = "form-group">
        <%= f.label :fixed_width_downsampled_url, :class => "col-sm-2 control-label" %>
        <div class = "col-sm-10">
          <%= f.text_field :fixed_width_downsampled_url, :class => "form-control", readonly: true %>
        </div>
      </div>
      <div class = "form-group">
        <%= f.label :keyword, :class => "col-sm-2 control-label" %>
        <div class = "col-sm-10">
          <%= f.text_field :keyword, :class => "form-control", readonly: true %>
        </div>
      </div>
    <% end %>
    <img src="<%= @gif[:image_original_url] %>" class="col-md-offset-2 img-responsive" alt="Responsive image">
  </div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissable" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="sr-only">Message: </span><%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class = "text-center">Built by <%= link_to "Laszlo Balogh", "http://laszlo.thebaloghs.com/" %></div>

app/views/layouts/_navbar.html.erb
<div class = "container">
<nav class="navbar navbar-default navbar-fixed-top navbar-pushin">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home" aria-hidden="true" id = "home-button"></span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
          <li class = "navbar-text"><strong>Hello, <%= current_user.name %></strong></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
            <div class="form-group navbar-text">
              <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-default" %>
            </div>
          <% else %>
            <form action = "/login" method = "POST" class="form-inline navbar-text">
              <input type = "hidden" name = "authenticity_token" />
              <div class="form-group">
                <input type="text" class="form-control" name = "username" id="username" placeholder="Username">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" name = "password" id="exampleInputPassword3" placeholder="Password">
              </div>
              <button type="submit" class="btn btn-default">Sign In</button>
            </form>
          <% end %>
        </li>
          <% if current_user.nil? %>        
        <li>
          <div class="form-group navbar-text">
            <%= link_to "Join The Fun", new_user_path, class: "btn btn-default" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifFavoriter from Laszlo Balogh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "/layouts/navbar" %>
    <%= render partial: "/layouts/flash" %>
    <%= yield %>

    <!-- Latest compiled and minified JavaScript 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->
    <footer class = "footer-row">
      <%= render partial: "/layouts/footer" %>
    </footer>

  </body>
</html>

app/views/users/new.html.erb
<div id = "page-content" class = "container">
<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
  <div class = "form-group">
    <%= f.label "Username:", :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :username, :class => "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <%= f.label "Name:", :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <%= f.label "Email:", :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.email_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <%= f.label "Password:", :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "col-sm-offset-2 col-sm-10">
      <%= f.submit "Register User", :class => "btn btn-default" %>
    </div>
  </div>

<% end %>
</div>

app/views/users/show.html.erb
<div>
  <p>User Details:</p>
</div>
<% if current_user.admin? %>
  <div>
    <%= link_to "User List", admin_users_path %>
  </div>
  <div>
    <%= link_to "Content Management", editor_gifs_path %>
  </div>
<% end %>

app/views/welcome/index.html.erb
Hello From Main Page